In [4]:
import pandas as pd

In [3]:
data1 = pd.read_csv("2016.csv")
data1

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2016-01-01,DL,1248,DTW,LAX,1935,1935.0,0.0,23.0,1958.0,...,309.0,285.0,249.0,1979.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,DL,1251,ATL,GRR,2125,2130.0,5.0,13.0,2143.0,...,116.0,109.0,92.0,640.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,DL,1254,LAX,ATL,2255,2256.0,1.0,19.0,2315.0,...,245.0,231.0,207.0,1947.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,DL,1255,SLC,ATL,1656,1700.0,4.0,12.0,1712.0,...,213.0,193.0,173.0,1590.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,DL,1256,BZN,MSP,900,1012.0,72.0,63.0,1115.0,...,136.0,188.0,121.0,874.0,72.0,0.0,52.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5617653,2016-12-31,NK,112,IAH,BWI,615,613.0,-2.0,12.0,625.0,...,170.0,167.0,144.0,1235.0,NaN,NaN,NaN,NaN,NaN,NaN
5617654,2016-12-31,NK,113,BWI,IAH,2108,2229.0,81.0,9.0,2238.0,...,214.0,200.0,182.0,1235.0,0.0,0.0,0.0,0.0,67.0,NaN
5617655,2016-12-31,NK,121,ORD,RSW,700,704.0,4.0,11.0,715.0,...,172.0,151.0,136.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
5617656,2016-12-31,NK,124,RSW,ORD,1704,1711.0,7.0,9.0,1720.0,...,183.0,170.0,154.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
5617657,2016-12-31,NK,126,FLL,MYR,2015,2208.0,113.0,21.0,2229.0,...,98.0,102.0,75.0,529.0,113.0,0.0,4.0,0.0,0.0,NaN

In [5]:
data2 = pd.read_csv("2017.csv")
data2

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2017-01-01,AA,1,JFK,LAX,800,831.0,31.0,25.0,856.0,...,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0,NaN
1,2017-01-01,AA,2,LAX,JFK,900,934.0,34.0,34.0,1008.0,...,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0,NaN
2,2017-01-01,AA,4,LAX,JFK,1130,1221.0,51.0,20.0,1241.0,...,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0,NaN
3,2017-01-01,AA,5,DFW,HNL,1135,1252.0,77.0,19.0,1311.0,...,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0,NaN
4,2017-01-01,AA,6,OGG,DFW,1855,1855.0,0.0,16.0,1911.0,...,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5674616,2017-12-31,UA,2421,IAH,LAS,750,744.0,-6.0,14.0,758.0,...,206.0,189.0,171.0,1222.0,NaN,NaN,NaN,NaN,NaN,NaN
5674617,2017-12-31,UA,2425,RSW,ORD,1611,1602.0,-9.0,12.0,1614.0,...,190.0,183.0,159.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
5674618,2017-12-31,UA,2426,SNA,DEN,1335,1334.0,-1.0,9.0,1343.0,...,134.0,123.0,104.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN
5674619,2017-12-31,UA,2427,LAS,SFO,1115,1107.0,-8.0,11.0,1118.0,...,99.0,92.0,66.0,414.0,NaN,NaN,NaN,NaN,NaN,NaN
5674620,2017-12-31,UA,2429,EWR,DEN,1510,1612.0,62.0,28.0,1640.0,...,270.0,266.0,227.0,1605.0,58.0,0.0,0.0,0.0,0.0,NaN

In [6]:
data3 = pd.read_csv("2018.csv")
data3

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2018-01-01,UA,2429,EWR,DEN,1517,1512.0,-5.0,15.0,1527.0,...,268.0,250.0,225.0,1605.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01,UA,2427,LAS,SFO,1115,1107.0,-8.0,11.0,1118.0,...,99.0,83.0,65.0,414.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-01,UA,2426,SNA,DEN,1335,1330.0,-5.0,15.0,1345.0,...,134.0,126.0,106.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01,UA,2425,RSW,ORD,1546,1552.0,6.0,19.0,1611.0,...,190.0,182.0,157.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01,UA,2424,ORD,ALB,630,650.0,20.0,13.0,703.0,...,112.0,106.0,83.0,723.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213441,2018-12-31,AA,1815,DCA,CLT,1534,1530.0,-4.0,20.0,1550.0,...,100.0,99.0,72.0,331.0,NaN,NaN,NaN,NaN,NaN,NaN
7213442,2018-12-31,AA,1816,CLT,DFW,1751,1757.0,6.0,18.0,1815.0,...,181.0,176.0,148.0,936.0,NaN,NaN,NaN,NaN,NaN,NaN
7213443,2018-12-31,AA,1817,CLT,MEM,2015,2010.0,-5.0,36.0,2046.0,...,112.0,128.0,88.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN
7213444,2018-12-31,AA,1818,CLT,RDU,1300,1323.0,23.0,11.0,1334.0,...,50.0,41.0,26.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN
7213445,2018-12-31,AA,1818,RDU,CLT,1435,1443.0,8.0,8.0,1451.0,...,71.0,59.0,44.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data4 = pd.read_csv("2019.csv")
data4

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,...,ARR_TIME,ARR_DELAY,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 20
0,2019-01-01,9E,3280,GNV,ATL,601.0,1.0,22.0,623.0,714.0,...,722.0,-1.0,51.0,300.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-01,9E,3281,MSP,CVG,1359.0,-5.0,15.0,1414.0,1629.0,...,1633.0,-36.0,75.0,596.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-01,9E,3282,DTW,CVG,1215.0,-5.0,18.0,1233.0,1323.0,...,1329.0,-16.0,50.0,229.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-01,9E,3283,TLH,ATL,1521.0,-6.0,14.0,1535.0,1618.0,...,1625.0,-14.0,43.0,223.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-01,9E,3284,ATL,FSM,1847.0,-15.0,18.0,1905.0,1935.0,...,1940.0,-25.0,90.0,579.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422032,2019-12-31,B6,846,MCO,SWF,1500.0,64.0,20.0,1520.0,1726.0,...,1731.0,52.0,126.0,989.0,52.0,0.0,0.0,0.0,0.0,NaN
7422033,2019-12-31,B6,854,DCA,BOS,1414.0,-6.0,15.0,1429.0,1526.0,...,1533.0,-17.0,57.0,399.0,NaN,NaN,NaN,NaN,NaN,NaN
7422034,2019-12-31,B6,860,PHL,BOS,652.0,-8.0,12.0,704.0,746.0,...,751.0,-34.0,42.0,280.0,NaN,NaN,NaN,NaN,NaN,NaN
7422035,2019-12-31,B6,861,BOS,SJU,812.0,-1.0,10.0,822.0,1245.0,...,1248.0,-27.0,203.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN
7422036,2019-12-31,B6,862,SJU,BOS,431.0,2.0,10.0,441.0,712.0,...,722.0,-16.0,211.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data = pd.concat([data1, data2,data3,data4], axis=0)

In [9]:
data

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27,OP_UNIQUE_CARRIER,Unnamed: 20
0,2016-01-01,DL,1248,DTW,LAX,1935.0,1935.0,0.0,23.0,1958.0,...,249.0,1979.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,DL,1251,ATL,GRR,2125.0,2130.0,5.0,13.0,2143.0,...,92.0,640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,DL,1254,LAX,ATL,2255.0,2256.0,1.0,19.0,2315.0,...,207.0,1947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,DL,1255,SLC,ATL,1656.0,1700.0,4.0,12.0,1712.0,...,173.0,1590.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,DL,1256,BZN,MSP,900.0,1012.0,72.0,63.0,1115.0,...,121.0,874.0,72.0,0.0,52.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422032,2019-12-31,NaN,846,MCO,SWF,NaN,1500.0,64.0,20.0,1520.0,...,126.0,989.0,52.0,0.0,0.0,0.0,0.0,NaN,B6,NaN
7422033,2019-12-31,NaN,854,DCA,BOS,NaN,1414.0,-6.0,15.0,1429.0,...,57.0,399.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
7422034,2019-12-31,NaN,860,PHL,BOS,NaN,652.0,-8.0,12.0,704.0,...,42.0,280.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
7422035,2019-12-31,NaN,861,BOS,SJU,NaN,812.0,-1.0,10.0,822.0,...,203.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
7422036,2019-12-31,NaN,862,SJU,BOS,NaN,431.0,2.0,10.0,441.0,...,211.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN

In [11]:
 data.to_csv(r'/Users/maggie/Desktop/Data Visualization/Term Project/Airline Delay Analysis.csv')

In [14]:
da = pd.read_csv('Airline Delay Analysis.csv')
da

/Users/maggie/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (2,17,29) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,...,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27,OP_UNIQUE_CARRIER,Unnamed: 20
0,0,2016-01-01,DL,1248,DTW,LAX,1935.0,1935.0,0.0,23.0,...,249.0,1979.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2016-01-01,DL,1251,ATL,GRR,2125.0,2130.0,5.0,13.0,...,92.0,640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2016-01-01,DL,1254,LAX,ATL,2255.0,2256.0,1.0,19.0,...,207.0,1947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2016-01-01,DL,1255,SLC,ATL,1656.0,1700.0,4.0,12.0,...,173.0,1590.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2016-01-01,DL,1256,BZN,MSP,900.0,1012.0,72.0,63.0,...,121.0,874.0,72.0,0.0,52.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25927757,7422032,2019-12-31,NaN,846,MCO,SWF,NaN,1500.0,64.0,20.0,...,126.0,989.0,52.0,0.0,0.0,0.0,0.0,NaN,B6,NaN
25927758,7422033,2019-12-31,NaN,854,DCA,BOS,NaN,1414.0,-6.0,15.0,...,57.0,399.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
25927759,7422034,2019-12-31,NaN,860,PHL,BOS,NaN,652.0,-8.0,12.0,...,42.0,280.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
25927760,7422035,2019-12-31,NaN,861,BOS,SJU,NaN,812.0,-1.0,10.0,...,203.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
25927761,7422036,2019-12-31,NaN,862,SJU,BOS,NaN,431.0,2.0,10.0,...,211.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN

In [15]:
data = da.drop('Unnamed: 0', 1)
data

/var/folders/1v/x5wmbpv968z1bmkh4vxwvqt80000gn/T/ipykernel_29918/3312206508.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data = da.drop('Unnamed: 0', 1)

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27,OP_UNIQUE_CARRIER,Unnamed: 20
0,2016-01-01,DL,1248,DTW,LAX,1935.0,1935.0,0.0,23.0,1958.0,...,249.0,1979.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,DL,1251,ATL,GRR,2125.0,2130.0,5.0,13.0,2143.0,...,92.0,640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,DL,1254,LAX,ATL,2255.0,2256.0,1.0,19.0,2315.0,...,207.0,1947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,DL,1255,SLC,ATL,1656.0,1700.0,4.0,12.0,1712.0,...,173.0,1590.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,DL,1256,BZN,MSP,900.0,1012.0,72.0,63.0,1115.0,...,121.0,874.0,72.0,0.0,52.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25927757,2019-12-31,NaN,846,MCO,SWF,NaN,1500.0,64.0,20.0,1520.0,...,126.0,989.0,52.0,0.0,0.0,0.0,0.0,NaN,B6,NaN
25927758,2019-12-31,NaN,854,DCA,BOS,NaN,1414.0,-6.0,15.0,1429.0,...,57.0,399.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
25927759,2019-12-31,NaN,860,PHL,BOS,NaN,652.0,-8.0,12.0,704.0,...,42.0,280.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
25927760,2019-12-31,NaN,861,BOS,SJU,NaN,812.0,-1.0,10.0,822.0,...,203.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN
25927761,2019-12-31,NaN,862,SJU,BOS,NaN,431.0,2.0,10.0,441.0,...,211.0,1674.0,NaN,NaN,NaN,NaN,NaN,NaN,B6,NaN

In [16]:
 data.to_csv(r'/Users/maggie/Desktop/Data Visualization/Term Project/Airline Delay Analysis.csv')